FROM ubuntu:latest

# RUN apt-get update && \
#     apt-get -y upgrade && \
#     apt-get install -y python3 python3-pip python-is-python3
 
# # RUN pip install "apache-airflow[celery]==2.5.3" \
# # --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.3/constraints-3.10.txt"
# RUN pip install mlflow

# RUN mlflow ui --backend-store-uri /data/mlflow --default-artifact-root /data/mlflow/artifacts --host 0.0.0.0 --port 5001